- name: playbook control using ansible fact
  become: true
  hosts: node
  tasks:
  - name: install nginx if redhat
    ansible.builtin.dnf:
     name: nginx
     state: present
    when: ansible_os_family == "RedHat"
    
  - name: install nginx if ubuntu
    ansible.builtin.apt:
     name: nginx
     state: present
    when: ansible_os_family == "Debian"