- name: install nginx
  hosts: local
  become: true
  connection: local
  tasks:
  - name: installing nginx server
    ansible.builtin.dnf:
     name: nginx
     state: present

  - name: restart nginx server
    ansible.builtin.service:
     name: nginx
     state: restarted

  - name: start nginx server
    ansible.builtin.service:
     name: nginx
     state: started
