- name: install nginx
  hosts: frontend
  become: true
  tasks:
  - name: installing nginx server
    ansible.builtin.dnf:
     name: nginx
     state: present

  - name: restart nginx server
    ansible.builtin.service:
     name: nginx
     state: restarted

  - name: start nginx server
    ansible.builtin.service:
     name: nginx
     state: started
