- name: comfigure shipping server
  hosts: shipping
  become: yes
  tasks:
  - name: install maven
    ansible.builtin.dnf:
     name: maven
     state: present
  
  - name: create roboshop system user
    ansible.builtin.user:
     name: roboshop
     system: true
     home: /app
     shell: /sbin/nologin

  - name: create directory
    ansible.builtin.file:
     path: /app
     state: directory

  - name: download shipping code
    ansible.builtin.get_url:
     url: https://roboshop-artifacts.s3.amazonaws.com/shipping-v3.zip
     dest: /tmp/shipping.zip

  - name: unzip the shipping code
    ansible.builtin.unarchive:
     src: /tmp/shipping.zip
     dest: /app
     remote_src: yes

  - name: install maven dependencies
    ansible.builtin.command: mvn clean package 
    args:
     chdir: /app

  - name: rename the target folder
    ansible.builtin.command: mv target/shipping-1.0.jar shipping.jar 
    args:
     chdir: /app

  - name: setup the shipping service
    ansible.builtin.copy:
     src: shipping.server
     dest: /etc/systemd/system/shipping.service

  - name: systemctl deamon reload
    ansible.builtin.systemd_service:
     daemon_reload: true
  

  - name: enable and start the shipping
    ansible.builtin.service:
     name: shipping
     state: started
     enabled: yes

  - name: install mysql client
    ansible.builtin.db\nf:
     name: mysql
     state: present

  - name: load the mysql data
    community.mysql.mysql_db:
     login_user: uroot
     login_password: -pRoboShop@1
     state: import
     login_host: mysql.srinunayak.online
     target: "{{ item }}"
     loop:
     - /app/db/schema.sql
     - /app/db/app-user.sql 
     - /app/db/master-data.sql

  - name: restart the shipping
    ansible.builtin.service:
     name: shipping
     state: restarted